formats:
  from:
    messages:
    - '%ct_expand% &a%ct_messages%'
    toolTips:
    - '&f[&6%ct_lang_source%&f] &f<&b%player_name%&f>'
    sounds:
    - BLOCK_NOTE_BLOCK_BELL; 1; 1
    - NOTE_PLING; 1; 1
  to:
    messages:
    - '&f<&b%player_name%&f> &a$ct_messages$'
    toolTips:
    - '&f[&6%ct_lang_source%&f] &a%ct_messages%'
    sounds:
    - ENTITY_EXPERIENCE_ORB_PICKUP; 1; 1
    - ORB_PICKUP; 1; 1

  to_console:
    messages:
    - '&f<&b%player_name%&f> &a$ct_messages$'
    toolTips:
    - '\t&f[&6%ct_lang_source%&f] &a%ct_messages%'

  from_entry:
    messages:
    - '&e$ct_messages$'
  to_entry:
    messages:
    - '&e$ct_messages$'

  from_exit:
    messages:
    - '&e$ct_messages$'
  to_exit:
    messages:
    - '&e$ct_messages$'

storage:
  type: sqlite
  host: localhost
  port: 3306
  database: ChatTranslator
  user: root
  password: password

auto-translate-others:
  access: true
  signs: true

server-uuid: "null"
chat-color-personalized: true
auto-update-config: true
show-native-chat:
  cancel-event: true
  clear-recipients: false
max-spam-per-tick: 150.0007
use-PAPI-format: true
check-updates: true
config-version: 0
default-lang: es
debug: false