default-lang: "es"
message-format: "&f<&b%player%&f> &f[&6%lang%&f] &7%msg%"
# Ejemplo de uso:     ^ PAPI ^         ^LOCAL^     LOCAL
#   Las variables LOCAL no son de PAPI y solo se pueden usar en este plugin.
message-color-personalized: true
auto-translate-chat: true
auto-format-chat: true