default-lang: "es"
message-format: "&f<&b%player%&f> &f[&6%sourceLang%&f] &e-> &f[&6$targetLang$&f] &a%msg%"
message-color-personalized: true
auto-format-messages: true
auto-translate-chat: true
debug: false