main: majhrs16.ct.main
version: 1.2.5
name: ChatTranslator
commands:
  ChatTranslator:
    description: Comando Principal.
  ct:
    description: Comando Principal.
  lang:
    description: Cambiar tu idioma.

permissions:
  ChatTranslator.lang.others:
    descriptions: Cambia el lenguaje de otro jugador.
    default: op