main: majhrs16.ct.ChatTranslator
version: v1.6.0
name: ChatTranslator
author: Majhrs16
softdepend: [PlaceHolderAPI, ConditionalEvents]

commands:
  ChatTranslator:
    description: Comando Principal.
  ct:
    description: Comando Principal.

permissions:
  ChatTranslator.admin:
    descriptions: Adminstra el plugin.
    default: op