version: 1.6.2
author: Majhrs16
name: ChatTranslator
main: majhrs16.ct.ChatTranslator
softdepend: [PlaceholderAPI, ConditionalEvents]

commands:
  chattranslator:
    description: Comando Principal.
  cht:
    description: Comando Principal.

permissions:
  ChatTranslator.admin:
    descriptions: Adminstra el plugin.
    default: op