main: majhrs16.ct.ChatTranslator
version: 1.3.5
name: ChatTranslator
author: Majhrs16
softdepend: [PlaceHolderAPI]

commands:
  ChatTranslator:
    description: Comando Principal.
  ct:
    description: Comando Principal.
  lang:
    description: Cambiar tu idioma.

permissions:
  ChatTranslator.admin:
    descriptions: Adminstra el plugin.
    default: op