main: majhrs16.ct.ChatTranslator
version: 1.6.2
name: ChatTranslator
author: Majhrs16
softdepend: [PlaceHolderAPI, ConditionalEvents]

commands:
  chattranslator:
    description: Comando Principal.
  cht:
    description: Comando Principal.

permissions:
  ChatTranslator.admin:
    descriptions: Adminstra el plugin.
    default: op