auto-translate-others:
  discord-reply: true
  discord: false
  access: true
  signs:
    enable: true
    wrapText: false

show-native-chat:
  cancel-event: true
  clear-recipients: false

storage:
  type: sqlite
  host: localhost
  port: 3306
  database: ChatTranslator
  user: root
  password: password

discord:
  bot-token: ''
  channels:
    chat:
      - "<Public channel ID>"
    deaths:
      - "<Public channel ID>"
    console:
      - "<PRIVATE channel ID>"
    server-status:
      - "<Public channel ID>"
    player-access:
      - "<Public channel ID>"

  sync:
    permissions:
      "<RoleID>": "DiscordTranslator.sync.test1"

    roles:
      "<RoleID>": "DiscordTranslator.sync.test2"

spam:
  max-ticks: 60
  max-messages: 7

server-uuid: 'null'
auto-update-config: true
use-PAPI-format: true
check-updates: true
config-version: 0
default-lang: es
debug: false
