auto-translate-others:
  discord-sync: true
  discord: false
  access: true
  signs:
    enable: false
    wrap-text: true

show-native-chat:
  cancel-event: true
  clear-recipients: false

storage:
  type: sqlite
  host: localhost
  port: 3306
  database: ChatTranslator
  user: root
  password: password

discord:
  bot-token: '<Your Bot Token>'
  channels:
    chat:
      - "<Public channel ID>"
    deaths:
      - "<Public channel ID>"
    replies:
      - "<Public channel ID>"
    console:
      - "<PRIVATE channel ID>"
    server-status:
      - "<Public channel ID>"
    player-access:
      - "<Public channel ID>"

  sync:
    - "<RoleID>   <-  <PermissionID>"
    - "<RoleID>    -> DiscordTranslator.sync.new"
    - "0123456789 <-> DiscordTranslator.sync.bidirectional"

spam:
  max-ticks: 60
  max-messages: 7

server-uuid: 'null'
auto-update-config: true
use-PAPI-format: true
check-updates: true
config-version: 0
default-lang: es
debug: false
