auto-translate-others:
  discord: false
  access: true
  signs:
    enable: true
    wrapText: false

show-native-chat:
  cancel-event: true
  clear-recipients: false

storage:
  type: sqlite
  host: localhost
  port: 3306
  database: ChatTranslator
  user: root
  password: password

discord:
  bot-token: ''
  channels:
    chat: []
    deaths: []
    console: []
    server-status: []
    player-access: []

spam:
  max-ticks: 20
  max-messages: 9

server-uuid: 'null'
auto-update-config: true
use-PAPI-format: true
check-updates: true
config-version: 0
default-lang: es
debug: false
