formats:
  from:
    messages:
    - '%ct_expand% &a%ct_messages%'
    toolTips:
    - '&f[&6%ct_lang_source%&f] &f<&b%player_name%&f>'
  to:
    messages:
    - '&f<&b%player_name%&f> &a$ct_messages$'
    toolTips:
    - '&f[&6%ct_lang_source%&f] &a%ct_messages%'
  to_console:
    messages:
    - '&f<&b%player_name%&f> &a$ct_messages$'
    toolTips:
    - '\t&f[&6%ct_lang_source%&f] &a%ct_messages%'
  to_discord:
    messages:
    - '<%player_name%> [%ct_lang_source%] $ct_messages$'

  from_entry:
    messages:
    - '&a+ &e%player_name% %ct_messages%'
  to_entry:
    messages:
    - '&a+ &e%player_name% $ct_messages$'

  from_exit:
    messages:
    - '&c- &e%player_name% %ct_messages%'
  to_exit:
    messages:
    - '&c- &e%player_name% $ct_messages$'

  from_private:
    messages:
    - '%ct_expand% &7%ct_messages%'
    toolTips:
    - '&f[&6%ct_lang_source%&f] &f<&7%player_name%&f>'
    sounds:
    - BLOCK_NOTE_BLOCK_BELL; 1; 1
    - NOTE_PLING; 1; 1
  to_private:
    messages:
    - '{"text": "&f<&7%player_name%&f> &7$ct_messages$", "clickEvent": {"action": "suggest_command", "value": "/tell %player_name% ..."}}'
    toolTips:
    - '&7Te han hablado al privado&f! &aHaz click para responder&f!'
    - '&f[&6%ct_lang_source%&f] &7%ct_messages%'
    sounds:
    - ENTITY_EXPERIENCE_ORB_PICKUP; 1; 1
    - ORB_PICKUP; 1; 1

  from_mention:
    messages:
      - '%ct_expand% &a%ct_messages%'
    toolTips:
      - '&f[&6%ct_lang_source%&f] &f<&a%player_name%&f>'
  to_mention:
    messages:
      - '{"text": "&f<&6%player_name%&f> &e$ct_messages$", "clickEvent": {"action": "suggest_command", "value": "@%player_name% "}}'
    toolTips:
      - '&eTe han mencionado&f! &aHaz click para responder&f!'
      - '&f[&6%ct_lang_source%&f] &e%ct_messages%'
    sounds:
      - ENTITY_EXPERIENCE_ORB_PICKUP; 1; 1
      - ORB_PICKUP; 1; 1

storage:
  type: sqlite
  host: localhost
  port: 3306
  database: ChatTranslator
  user: root
  password: password

auto-translate-others:
  discord: false
  access: true
  signs: true

discord:
  bot-token: ''
  channels:
    chat: []
    console: []
    server-status: []
    player-access: []

server-uuid: 'null'
auto-update-config: true
show-native-chat:
  cancel-event: true
  clear-recipients: false
max-spam-per-tick: 90.0009
use-PAPI-format: true
check-updates: true
config-version: 0
default-lang: es
debug: false