main: majhrs16.cht.ChatTranslator
name: ChatTranslator
author: Majhrs16
load: STARTUP
version: 1.7.12

softdepend:
- PlaceholderAPI
- ConditionalEvents

permissions:
  ChatTranslator.admin:
    descriptions: Administrate the plugin.
    default: op